language: groovy
jdk:
- openjdk8
sudo: false
branches:
  only:
  - master
  - hotfix
  - develop
  - EYA-enhancements
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/

after_success:
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && travis_retry ./gradlew publish'
env:
  global:
  - secure: XuqIReYymPo+LQWKa1mRm0rollfvmVYV4+Hx0lMcunbu3eNsFc5GrRmocpo2r2z0N5bbV/0tHTQXylyvvvKaEFvbRx7KGh/tZI8/EOrouwQ9CG1YMJP33Kn4kOmETP5EO69RoMqBgsaMr3EFc1z/EI38lZWLR9kcA/awwBCAMZ0=
  - secure: KAIqn+fMFEvP0uMlTOiKp60ps/ev87O07GaHTCNBzLhrQ1C63T+gSCJD28ADPQlVM7PtSqmuGv+ihNnxBP/5YWFY6LK/DXXYrigaDpGSkSrIKdv5Yt0IJZliHp1XmYevVkRCYbGXKaLZbYWV1hnKNI4vZa0K8HOoFtaR81U+rho=
