---
grails:
    profile: web
    project:
        groupId: 'au.org.ala'
    codegen:
        defaultPackage: au.org.ala.hub
    config:
        locations:
            - classpath:plugin.groovy # biocache-hubs
            - file:/data/ala-hub/config/ala-hub-config.properties
            - file:/data/ala-hub/config/ala-hub-config.yml
            - file:/data/ala-hub/config/ala-hub-config.groovy
    spring:
        transactionManagement:
            proxies: false
    gorm:
        # Whether to autowire entities.
        # Disabled by default for performance reasons.
        autowire: false
        reactor:
            # Whether to translate GORM events into Reactor events
            # Disabled by default for performance reasons
            events: false
    exceptionresolver:
        params:
            exclude:
                - 'password'
    plugins:
        twitterbootstrap:
            fixtaglib: true
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
        description: 'Atlas of Living Australia'
spring:
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false
# Spring Actuator Endpoints are Disabled by Default
endpoints:
    enabled: true
    jmx:
        enabled: true
        unique-names: true

---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - 'Gecko'
                        - 'WebKit'
                        - 'Presto'
                        - 'Trident'
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    enable:
        native2ascii: true
    web:
        disable:
            multipart: false
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    json:
        legacy:
            builder: false
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlets: html
                taglib: none
                staticparts: none
    serverURL: 'https://biocache.ala.org.au'

---
serverName: 'https://biocache.ala.org.au'

skin:
    layout: 'ala-main'
    orgNameLong: 'Atlas of Living Australia'
    orgNameShort: 'ALA'
    headerUrl: 'classpath:resources/generic-header.jsp'     # can be external URL
    footerUrl: 'classpath:resources/generic-footer.jsp'     # can be external URL
    fluidLayout: true                                       # true or false
    exploreUrl: 'https://www.ala.org.au/explore-by-location/'
    taxaLinks:
        baseUrl: 'https://bie.ala.org.au/species/'
    useAlaSpatialPortal: true
    useAlaBie: true
    dataQualityLink:
        show: false                                         # set to true via external config
        url: 'https://biocache-dq-test.ala.org.au'
        text: 'Try the new search interface with automatic filtering based on data quality metrics'
        tooltip: 'Click to run the current search on our test server'


privacyPolicy: 'http://www.ala.org.au/about/terms-of-use/privacy-policy/'

headerAndFooter:
    version: "1"

security:
    cas:
        enabled: false # default is true, undefined behaviour if this omitted
    oidc:
        enabled: true # default is false
        discoveryUri: 'https://auth-test.ala.org.au/cas/oidc/.well-known'
        clientId: 'change me'
        secret: 'change me'
        scope: 'openid profile email'
        allowUnsignedIdTokens: true

webservice:
    jwt: true

auth:
    admin_role: 'ROLE_ADMIN'

environments:
    development:
        grails:
            serverURL: "http://localhost:8081/ala-hub"
        server:
            port: 8081
            servlet:
                contextPath: '/ala-hub'
