---
grails:
    profile: web
    codegen:
        defaultPackage: au.org.ala.hub
    config:
        locations:
            - classpath:plugin.groovy # biocache-hubs
            - file:/data/ala-hub/config/ala-hub-config.properties
            - file:/data/ala-hub/config/ala-hub-config.yml
            - file:/data/ala-hub/config/ala-hub-config.groovy
    spring:
        transactionManagement:
            proxies: false
    gorm:
        # Whether to autowire entities.
        # Disabled by default for performance reasons.
        autowire: false
        reactor:
            # Whether to translate GORM events into Reactor events
            # Disabled by default for performance reasons
            events: false
    plugins:
        twitterbootstrap:
            fixtaglib: true
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
        description: 'Atlas of Living Australia'
spring:
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false
# Spring Actuator Endpoints are Disabled by Default
endpoints:
    enabled: true
    jmx:
        enabled: true
        unique-names: true

---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlets: html
                taglib: none
                staticparts: none
---
skin:
    layout: "main"
    orgNameLong: "Atlas of Living Australia"
    orgNameShort: "ALA"
privacyPolicy: "http://www.ala.org.au/about/terms-of-use/privacy-policy/"

security:
    cas:
        uriFilterPattern: '/admin.*,/alaAdmin.*,/download.*'
        authenticateOnlyIfLoggedInPattern: '/occurrences/(?!.+userAssertions|facet.+).+,/explore/your-area,/query,/proxy/download/.*'
        uriExclusionFilterPattern: '/occurrences/shapeUpload,/images.*,/css.*,/js.*,.*json,/help/.*'

server:
    contextPath: /ala-hub

environments:
    development:
        grails:
            serverURL: "https://devt.ala.org.au/ala-hub"
        security:
            cas:
                appServerName: "https://auth.ala.org.au"
    test:
        security:
            cas:
                appServerName: "https://auth.ala.org.au"
    production:
        grails:
            serverURL: "https://biocache.ala.org.au"
        security:
            cas:
                appServerName: "https://auth.ala.org.au"
