---
grails:
    profile: web
    codegen:
        defaultPackage: au.org.ala.hub
    config:
        locations:
            - classpath:plugin.groovy # biocache-hubs
            - file:/data/ala-hub/config/ala-hub-config.properties
            - file:/data/ala-hub/config/ala-hub-config.yml
            - file:/data/ala-hub/config/ala-hub-config.groovy
    spring:
        transactionManagement:
            proxies: false
    gorm:
        # Whether to autowire entities.
        # Disabled by default for performance reasons.
        autowire: false
        reactor:
            # Whether to translate GORM events into Reactor events
            # Disabled by default for performance reasons
            events: false
    plugins:
        twitterbootstrap:
            fixtaglib: true
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
        description: 'Atlas of Living Australia'
spring:
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false
# Spring Actuator Endpoints are Disabled by Default
endpoints:
    enabled: true
    jmx:
        enabled: true
        unique-names: true

---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlets: html
                taglib: none
                staticparts: none
---
skin:
    layout: "ala-main"
    orgNameLong: "Atlas of Living Australia"
    orgNameShort: "ALA"
privacyPolicy: "http://www.ala.org.au/about/terms-of-use/privacy-policy/"

headerAndFooter:
    version: "1"

security:
    cas:
        casServerName: 'https://auth.ala.org.au'
        loginUrl: 'https://auth.ala.org.au/cas/login'
        logoutUrl: 'https://auth.ala.org.au/cas/logout'
        casServerUrlPrefix: 'https://auth.ala.org.au/cas'

        bypass: false # set to true for non-ALA deployment
        gateway: false
        uriExclusionFilterPattern: '/assets.*,/images.*,/css.*,/js.*,/less.*,'
        uriFilterPattern: '/alaAdmin.*'
        #if false, ticket params always proceed
        #true, only processes urls listed in authenticateOnlyIfLoggedInFilterPattern
        applyUriFiltersToTicketValidation: false
        authenticateOnlyIfLoggedInFilterPattern: '/occurrences/(?!.+userAssertions|facet.+).+,/explore/your-area,/query,/proxy/download/.*'
        disableCAS: false


environments:
    development:
        grails:
            serverURL: "http://devt.ala.org.au:8081/ala-hub"
        server:
            port: 8081
            servlet:
                contextPath: '/ala-hub'

        security:
            cas:
                appServerName: "http://dev.ala.org.au:8081/"
    test:
        security:
            cas:
                appServerName: "http://dev.ala.org.au:8081"
    production:
        grails:
            serverURL: "https://biocache.ala.org.au"
        security:
            cas:
                appServerName: "https://auth.ala.org.au"
